/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.rockscache.avro.proto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KeyValuePairBatchResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7527172736844133840L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KeyValuePairBatchResponse\",\"namespace\":\"org.rockscache.avro.proto\",\"fields\":[{\"name\":\"payload\",\"type\":{\"type\":\"array\",\"items\":\"boolean\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KeyValuePairBatchResponse> ENCODER =
      new BinaryMessageEncoder<KeyValuePairBatchResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KeyValuePairBatchResponse> DECODER =
      new BinaryMessageDecoder<KeyValuePairBatchResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<KeyValuePairBatchResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<KeyValuePairBatchResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KeyValuePairBatchResponse>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this KeyValuePairBatchResponse to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a KeyValuePairBatchResponse from a ByteBuffer. */
  public static KeyValuePairBatchResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<java.lang.Boolean> payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KeyValuePairBatchResponse() {}

  /**
   * All-args constructor.
   * @param payload The new value for payload
   */
  public KeyValuePairBatchResponse(java.util.List<java.lang.Boolean> payload) {
    this.payload = payload;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return payload;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: payload = (java.util.List<java.lang.Boolean>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'payload' field.
   * @return The value of the 'payload' field.
   */
  public java.util.List<java.lang.Boolean> getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.util.List<java.lang.Boolean> value) {
    this.payload = value;
  }

  /**
   * Creates a new KeyValuePairBatchResponse RecordBuilder.
   * @return A new KeyValuePairBatchResponse RecordBuilder
   */
  public static org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder newBuilder() {
    return new org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder();
  }

  /**
   * Creates a new KeyValuePairBatchResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KeyValuePairBatchResponse RecordBuilder
   */
  public static org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder newBuilder(org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder other) {
    return new org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder(other);
  }

  /**
   * Creates a new KeyValuePairBatchResponse RecordBuilder by copying an existing KeyValuePairBatchResponse instance.
   * @param other The existing instance to copy.
   * @return A new KeyValuePairBatchResponse RecordBuilder
   */
  public static org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder newBuilder(org.rockscache.avro.proto.KeyValuePairBatchResponse other) {
    return new org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder(other);
  }

  /**
   * RecordBuilder for KeyValuePairBatchResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KeyValuePairBatchResponse>
    implements org.apache.avro.data.RecordBuilder<KeyValuePairBatchResponse> {

    private java.util.List<java.lang.Boolean> payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.payload)) {
        this.payload = data().deepCopy(fields()[0].schema(), other.payload);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing KeyValuePairBatchResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(org.rockscache.avro.proto.KeyValuePairBatchResponse other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.payload)) {
        this.payload = data().deepCopy(fields()[0].schema(), other.payload);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'payload' field.
      * @return The value.
      */
    public java.util.List<java.lang.Boolean> getPayload() {
      return payload;
    }

    /**
      * Sets the value of the 'payload' field.
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder setPayload(java.util.List<java.lang.Boolean> value) {
      validate(fields()[0], value);
      this.payload = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'payload' field.
      * @return This builder.
      */
    public org.rockscache.avro.proto.KeyValuePairBatchResponse.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KeyValuePairBatchResponse build() {
      try {
        KeyValuePairBatchResponse record = new KeyValuePairBatchResponse();
        record.payload = fieldSetFlags()[0] ? this.payload : (java.util.List<java.lang.Boolean>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KeyValuePairBatchResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<KeyValuePairBatchResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KeyValuePairBatchResponse>
    READER$ = (org.apache.avro.io.DatumReader<KeyValuePairBatchResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
